# Configuration for the Node.js server
nodeServer:
  replicas: 3
  image: yosefsha/node-crdt-demo:latest

# Configuration for the React client
reactClient:
  replicas: 3
  image: yosefsha/react-crdt-demo:latest
  apiDomain: "http://node-server-clusterip:3001"

# Configuration for the Kubernetes Service
service:
  port: 80

# Configuration for the Kubernetes ServiceAccount
serviceAccount:
  create: true
  name: ""

# Configuration for the Kubernetes Ingress
ingress:
  enabled: false # Enable or disable the Ingress resource
  annotations:
    {} # Annotations for the Ingress resource
    # Example annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local # Hostname for the Ingress
      paths: [] # Paths to route to the service
  tls: [] # TLS configuration for the Ingress
  # Example TLS configuration:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
