services:
  traefik:
    image: traefik:v2.11
    command:
      - "--log.level=DEBUG" # <--- Add this line for verbose logs
      - "--api.dashboard=true"
      - "--api=true"
      - "--api.insecure=true" # This allows dashboard without defining a custom router
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network

  server:
    labels:
      - "traefik.http.routers.server.rule=PathPrefix(`/api`, `/socket`)"
      - "traefik.http.services.server.loadbalancer.server.port=5001"

    build: ./server
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
      - JWT_SECRET=supersecret
  client:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.routers.client.priority=1"
      - "traefik.http.services.client.loadbalancer.server.port=80"

    build:
      context: ./rclient
      args:
        API_URL: /api
        MYENV: "docker"
        SOCKET_PATH: /socket
    networks:
      - app-network
    depends_on:
      - server

  auth:
    build: ./auth
    environment:
      - JWT_SECRET=supersecret
      - MONGO_URI=mongodb://mongo:27017/authdb
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - app-network

  rabbit-mq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    networks:
      - app-network

  rabbit-mq-ui:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

  enrich-worker:
    build: ./enrich-worker
    environment:
      - RABBIT_URL=amqp://rabbit-mq
      - SECRETS_PATH=./run/secrets/apiconf.json
    volumes:
      - ./secrets/apiconf.json:/run/secrets/apiconf.json:ro
    networks:
      - app-network
    depends_on:
      - rabbit-mq

networks:
  app-network:

volumes:
  mongo-data:
