services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # Entry point for all routing
      - "8080:8080" # Optional: Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network

  server:
    labels:
      - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
      - "traefik.http.services.server.loadbalancer.server.port=5001"

    build: ./server
    container_name: server
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
      - JWT_SECRET=supersecret

  client:
    labels:
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.services.client.loadbalancer.server.port=80"

    build:
      context: ./rclient
      args:
        API_URL: http://localhost/api
        MYENV: "docker"
    container_name: rclient
    networks:
      - app-network
    depends_on:
      - server

  auth:
    build: ./auth
    container_name: auth
    environment:
      - JWT_SECRET=supersecret
      - MONGO_URI=mongodb://mongo:27017/authdb
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - app-network

  rabbit-mq:
    image: rabbitmq:3
    container_name: rabbit-mq
    ports:
      - "5672:5672"
    networks:
      - app-network

  rabbit-mq-ui:
    image: rabbitmq:3-management
    container_name: rabbit-mq-ui
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
