# this is a deployment file for the server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: crdt-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crdt-server
  template:
    metadata:
      labels:
        app: crdt-server
    spec:
      containers:
        - name: crdt-demo-server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
# this is a service for the server
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: crdt-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
