apiVersion: eksctl.io/v1alpha5 # API version for eksctl configuration
kind: ClusterConfig # Kind of the resource, in this case, a ClusterConfig

metadata:
  name: eks-demo-cluster # Name of the EKS cluster
  region: us-east-1 # AWS region where the cluster will be created

# Node group configuration
nodeGroups:
  - name: ng-1 # Name of the node group
    instanceType: t3.small # EC2 instance type for the nodes
    desiredCapacity: 2 # Desired number of nodes in the node group
    volumeSize: 5 # Size of the EBS volume attached to each node (in GB)
    ssh:
      allow: false # Allow SSH access to the nodes (default: false)
      # publicKeyName: eks-demo-key # Name of the SSH key pair to use for SSH access
    privateNetworking: false # Enable private networking for the nodes (default: false)
    securityGroups: # Security groups for the nodes
      withShared: false # Use shared security groups (default: false)
      withLocal: false # Use local security groups (default: false)
    labels: { role: worker } # Labels to apply to the nodes
    tags: # Tags to apply to the nodes
      nodegroup-role: worker # Tag indicating the role of the node group
    iam:
      withAddonPolicies: # IAM policies to attach to the node group
        autoScaler: false # Allow the cluster autoscaler to scale the node group (default: false)
        externalDNS: false # Allow external DNS management (default: false)
        certManager: false # Allow cert-manager to manage certificates (default: false)
        appMesh: false # Allow App Mesh integration (default: false)
        ebs: false # Allow EBS volume management (default: false)
        fsx: false # Allow FSx integration (default: false)
        efs: false # Allow EFS integration (default: false)
        albIngress: false # Allow ALB Ingress controller integration (default: false)
        xRay: false # Allow AWS X-Ray integration (default: false)
        cloudWatch: false # Allow CloudWatch integration (default: false)
        imageBuilder: false # Allow Image Builder integration (default: false)
